spring:
    application:
        name: concurrencySample
   
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
              
              dialect : org.hibernate.dialect.MySQLDialect
              show_sql: true
              current_session_context_class:  org.springframework.orm.hibernate4.SpringSessionContext
    messages:
        basename: appconfig
    mvc:
        favicon:
            enabled: false
    aop:
        auto: true
    datasource:
        url: jdbc:mysql://localhost:3306/concurrencySample
        username: root
        password: root
        validationQuery: SELECT 1
        testOnBorrow: true
        hikari:
            minimum-idle: 1
            maximum-pool-size: 20
            pool-name: yourPoolName
            maxLifetime:  30
            idleTimeout:  30000
            connectionTimeout:  30000
        
server:
    compression:
        enabled: true
    port: 8087
    servlet-path: /rest
    
# Hibernate
hibernate:
    transaction.factory_class:  org.hibernate.transaction.JTATransactionFactory
    current_session_context_class:  jta
    ddl-auto : none
entitymanager:
    packagesToScan: org.cocurrency.model.*
# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    logging:
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: true
            # edit spring.metrics.export.delay-millis to set report frequency
